### ISSUE TITLE
PEP 8 - Style

### ISSUE THREAD

**Issue by m-haisham** [yangman946/WallPaperChanger#1]
Noticed that you were not following the python [style guidelines](https://www.python.org/dev/peps/pep-0008/).

### The essentials are:

Variables, function/method, python file and module names should be in `snake_case`.

And constants in `SCREAMING_SNAKE_CASE`.

If you have no intention of changing the style, feel free to close the issue.

**Comment by yangman946** [comment]
This issue is fixed in 4ced23993d8e6d756547b2595812ec75b11a7142 
I will close this issue now.
