### ISSUE TITLE
CurrentUrl = ??

### ISSUE THREAD

**Issue by CherifBouabdallah** [yangman946/WallPaperChanger#2]
Hello, 

I am a beginner in Python and I changed the Url's but still my wallpaper isn't changing.
i changed the pic_url and the api key (APIKEYOWM)

but on the website there are lots of different url's for the CurrentUrl = ...
so which one do I use ? 
are those 3 url's the only thing i need to change ?

thanks and sorry if i asked a useless question (i am also learning english)

**Comment by yangman946** [comment]
Are you getting a specific error?

Make sure you haven't placed the api key inside of `os.getenv("API_KEY")` this is an environment variable so you could either create your own .env file or just add your api key like this: `APIKEYOWM = "YOUR KEY"`

Otherwise try cloning the newest version of this repository and report any errors.

**Comment by CherifBouabdallah** [comment]
i updated the program and now there are only two links but nothing happend
I think the problem is that the program just dosen't start.

**Comment by CherifBouabdallah** [comment]
here is the error 


C:\Users\chena\3D Objects\WALLPAPER\WallPaperChanger-main>python -m wallpaperChanger.mainScript
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\chena\3D Objects\WALLPAPER\WallPaperChanger-main\wallpaperChanger\mainScript.py", line 29, in <module>
    CurrentUrl = f"http://api.openweathermap.org/data/2.5/weather?q={2661187}&mode=xml&units=metric&APPID={a65b38088fbd3479f436ad8c984cfd5d}"  # <---
NameError: name 'a65b38088fbd3479f436ad8c984cfd5d' is not defined

**Comment by yangman946** [comment]
When you add your city name and API key, you are to replace the curly brackets as well. For example, `...?q=sydney&` instead of
 `...?q={sydney}&`

**Comment by CherifBouabdallah** [comment]
It worked !

thanks and sorry cause it was a small mistake
