### ISSUE TITLE
Issue with task scheduler 

### ISSUE THREAD

**Issue by JordanLeich** [yangman946/WallPaperChanger#5]
I'm not sure why but I just cannot manage to get the task scheduler to run either the mainScript.py or the bat file. If I just run the program naturally using the mainScript.py or bat through an idle or file explorer, it runs just fine and the wallpaper changes successfully but when running the scheduler automatically or manually, it opens python for a slight second and closes without changes the desktop wallpaper. If maybe the program could be in an executable format such as an exe format, this might resolve the issue but I'm still not sure.
![scheduler](https://user-images.githubusercontent.com/57107961/132438008-8a94f3da-ebd0-404b-9e59-ed20d946e780.PNG)

**Comment by yangman946** [comment]
Ok, I was able to replicate your issue, I have released a patch for the run.bat file: on the first line replace the {} with the location of the batch script, try adding it to task scheduler again.

**Comment by JordanLeich** [comment]
Ok thanks, I will try this out in a little bit!

**Comment by JordanLeich** [comment]
@yangman946 I finally got it working now with the task scheduler, the reason why it wasn't working for me was because I changed wallpaperChanger.settings to settings and it broke the batch file from working properly. 
![image](https://user-images.githubusercontent.com/57107961/132449540-e67f4743-8758-4765-a123-673de04d5f9e.png)
